# Generated by Django 2.0.6 on 2018-06-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=80)),
                ('submission_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=100)),
                ('full_body', models.TextField()),
            ],
        ),
    ]
